name: build-latest-image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/docker.yaml
      - src/**
      - package.json
      - bun.lock
      - migrations.sql

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/mocdaniel/yay-or-nay
          tags: |
            type=raw,value=latest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
